// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtuWGnI3TtLiecCf7rwr3F7usdz-Piug',
    appId: '1:672209606331:web:c7d2d2e94a6475feab3b9e',
    messagingSenderId: '672209606331',
    projectId: 'bpospro-b1305',
    authDomain: 'bpospro-b1305.firebaseapp.com',
    storageBucket: 'bpospro-b1305.firebasestorage.app',
    measurementId: 'G-LH9YR9DXMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4c3pRDdfqJah0pBMoZTaLKpbzeg3sYJw',
    appId: '1:672209606331:android:a8d53544e84162d9ab3b9e',
    messagingSenderId: '672209606331',
    projectId: 'bpospro-b1305',
    storageBucket: 'bpospro-b1305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjgL5Zou-2sfMnexkw90x72w4kJoI6Fo',
    appId: '1:672209606331:ios:b42a7210ed4f7573ab3b9e',
    messagingSenderId: '672209606331',
    projectId: 'bpospro-b1305',
    storageBucket: 'bpospro-b1305.firebasestorage.app',
    iosBundleId: 'com.maantheme.mobilepos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjgL5Zou-2sfMnexkw90x72w4kJoI6Fo',
    appId: '1:672209606331:ios:0092f5ed08927e8aab3b9e',
    messagingSenderId: '672209606331',
    projectId: 'bpospro-b1305',
    storageBucket: 'bpospro-b1305.firebasestorage.app',
    iosBundleId: 'com.maantheme.mobilepos.posproMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAtuWGnI3TtLiecCf7rwr3F7usdz-Piug',
    appId: '1:672209606331:web:a137d9f3b2a8117cab3b9e',
    messagingSenderId: '672209606331',
    projectId: 'bpospro-b1305',
    authDomain: 'bpospro-b1305.firebaseapp.com',
    storageBucket: 'bpospro-b1305.firebasestorage.app',
    measurementId: 'G-5YPZP2SGB4',
  );
}
